export const GET_AUTHORS = 'AUTHORS/GET_AUTHORS';
export const CLEAR_AUTHOR = 'AUTHORS/CLEAR_AUTHOR';
export const GET_AUTORS_COURSE = 'AUTHORS/GET_AUTORS_COURSE';
export const APPROVE_AUTHOR_COURSE = 'AUTHORS/APPROVE_AUTHOR_COURSE';
export const DISAPPROVE_AUTHOR_COURSE = 'AUTHORS/DISAPPROVE_AUTHOR_COURSE';
