export const GET_AUTHORS = 'AUTHORS/GET_AUTHORS';
export const CLEAR_AUTHOR = 'AUTHORS/CLEAR_AUTHOR';
export const ADD_AUTHOR = 'AUTHORS/ADD_AUTHOR';
export const DELETE_AUTOR = 'AUTHORS/DELETE_AUTOR';
export const ADD_AUTHOR_TO_COURSE = 'AUTHORS/ADD_AUTHOR_TO_COURSE';
export const DELETE_AUTHOR_FROM_COURSE = 'AUTHORS/DELETE_AUTHOR_FROM_COURSE';
