export const GET_COURSES = 'COURSES/GET_COURSES';
export const UPDATE_COURSES = 'COURSES/UPDATE_COURSES';
export const ADD_COURSE = 'COURSE/ADD_COURSE';
export const DELETE_COURSE = 'COURSE/DELETE_COURSE';
